kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  ### individual loopbacks can break on docker-for-mac: https://github.com/stealthybox/multicluster-gitops/issues/1#issuecomment-733131819
  # apiServerAddress: "127.0.0.3"
  # apiServerPort: 6443
  disableDefaultCNI: true
  podSubnet: 10.52.0.0/16
  serviceSubnet: 10.102.0.0/19
nodes:
- role: control-plane
- role: worker
  ### these can be useful if you want to create an HTTP/HTTPS ingress hosted via NodePort, forwarded to your host
  # extraPortMappings:
  # - containerPort: 31080
  #   hostPort: 80
  #   listenAddress: "127.0.0.3"
  #   protocol: tcp
  # - containerPort: 31443
  #   hostPort: 443
  #   listenAddress: "127.0.0.3"
  #   protocol: tcp
